version: '3.8'

services:

  app:
    build: .
    restart: always
    command: daphne test_django_channels.asgi:application -b 0.0.0.0 -p 8000
    ports:
      - "8000:8000"

  redis:
    build: .
    restart: always
    command: redis-server  --protected-mode no
    expose:
      - 6379