version: '3.8'

services:
  #nginx service
  web:
    image: nginx:alpine
    depends_on:
      - app
      - ws_backend
    ports:
      - "8080:8010"
    volumes:
      - ./conf.d:/etc/nginx/conf.d

  app:
    build:
      context: .
      dockerfile: wsgi.Dockerfile
    restart: always

  ws_backend:
    build:
      context: .
      dockerfile: asgi.Dockerfile
    restart: always

  redis:
    container_name: redis
    image: redis
    restart: unless-stopped
    ports:
      - '6379:6379'

#  redis:
#    build: .
#    restart: always
#    command: redis-server  --protected-mode no
#    expose:
#      - 6379