version: '3.8'

services:

  app:
    build: .
    restart: always
#    command: daphne test_django_channels.asgi:application -b 0.0.0.0 -p 8000
    ports:
      - '8080:8000'

  redis:
    container_name: redis
    image: redis
    restart: unless-stopped
    expose:
        - 6379